/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as CommitteeYearRouteImport } from './routes/$committee.$year'
import { Route as CommitteeSubTypeYearRouteImport } from './routes/$committee.$subType.$year'
import { Route as TransactionsCommitteeTypeYearRouteImport } from './routes/transactions.$committee.$type.$year'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeYearRoute = CommitteeYearRouteImport.update({
  id: '/$committee/$year',
  path: '/$committee/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeSubTypeYearRoute = CommitteeSubTypeYearRouteImport.update({
  id: '/$committee/$subType/$year',
  path: '/$committee/$subType/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsCommitteeTypeYearRoute =
  TransactionsCommitteeTypeYearRouteImport.update({
    id: '/transactions/$committee/$type/$year',
    path: '/transactions/$committee/$type/$year',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/$committee/$year': typeof CommitteeYearRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$committee/$subType/$year': typeof CommitteeSubTypeYearRoute
  '/transactions/$committee/$type/$year': typeof TransactionsCommitteeTypeYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/$committee/$year': typeof CommitteeYearRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$committee/$subType/$year': typeof CommitteeSubTypeYearRoute
  '/transactions/$committee/$type/$year': typeof TransactionsCommitteeTypeYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/$committee/$year': typeof CommitteeYearRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/$committee/$subType/$year': typeof CommitteeSubTypeYearRoute
  '/transactions/$committee/$type/$year': typeof TransactionsCommitteeTypeYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$committee/$year'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$committee/$subType/$year'
    | '/transactions/$committee/$type/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$committee/$year'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$committee/$subType/$year'
    | '/transactions/$committee/$type/$year'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$committee/$year'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$committee/$subType/$year'
    | '/transactions/$committee/$type/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  CommitteeYearRoute: typeof CommitteeYearRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  CommitteeSubTypeYearRoute: typeof CommitteeSubTypeYearRoute
  TransactionsCommitteeTypeYearRoute: typeof TransactionsCommitteeTypeYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$committee/$year': {
      id: '/$committee/$year'
      path: '/$committee/$year'
      fullPath: '/$committee/$year'
      preLoaderRoute: typeof CommitteeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$committee/$subType/$year': {
      id: '/$committee/$subType/$year'
      path: '/$committee/$subType/$year'
      fullPath: '/$committee/$subType/$year'
      preLoaderRoute: typeof CommitteeSubTypeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$committee/$type/$year': {
      id: '/transactions/$committee/$type/$year'
      path: '/transactions/$committee/$type/$year'
      fullPath: '/transactions/$committee/$type/$year'
      preLoaderRoute: typeof TransactionsCommitteeTypeYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  CommitteeYearRoute: CommitteeYearRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  CommitteeSubTypeYearRoute: CommitteeSubTypeYearRoute,
  TransactionsCommitteeTypeYearRoute: TransactionsCommitteeTypeYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
